name: owl
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.1
  delightful_toast: ^1.1.0
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  get_it: ^7.7.0
  grouped_list: ^6.0.0
  hexcolor: ^3.0.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  path: ^1.9.0
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  tuple: ^2.0.2
  uuid: ^4.4.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Almendra
      fonts:
        - asset: assets/fonts/Almendra-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almendra-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Almendra-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almendra-BoldItalic.ttf
          weight: 700
          style: italic
